### ISSUE TITLE
Prepare project for new life as a Sinon.JS project

### ISSUE THREAD

**Issue by mroderick** [sinonjs/samsam#17]
#### Code
- [x] Configure `mocha` and `referee`
- [x] Port tests to `mocha`
- [x] Use `nyc` for test coverage
- [x] Add `.editorconfig`
- [x] ESLint
    - [x] Use `eslint-config-sinon`
    - [x] Use `eslint-plugin-ie11`
    - [x] Use `eslint-plugin-mocha`
    - [x] Use `lint-staged` and `husky` for pre-commit hook
- [x] Remove UMD wrapper from source files
- [x] Create UMD wrapped `dist` version (re-use solution from [sinonjs/referee](https://github.com/sinonjs/referee))

#### Third party services
- [x] Run tests in node LTS versions (4, 6, 8) on Travis
- [x] Push coverage report to coveralls
- [x] Configure bithound.io for repository

#### Repository
- [x] Port documentation to [`MkDocs`](http://www.mkdocs.org) and publish to GitHub Pages
- [x] Add CONTRIBUTING.md
- [x] Add pull request template
- [x] Add new issue template
- [x] Add `.github/stale.yml` and create `pinned` and `stale` labels
- [x] Protect `master` branch from force pushes, including for administrators

#### NPM
- [x] Add `.npmignore` / `files` section and filter out files that package consumers would not want
- [x] Publish module under `@sinonjs` scope with a new version
- [x] Deprecate old package on npm (@mroderick can do this)

**Comment by scripter-co** [comment]
@mroderick who needs to setup coveralls?

**Comment by mroderick** [comment]
> @mroderick who needs to setup coveralls?

That would be me. I've done that and in #29 have added a badge to `README.md`

**Comment by mroderick** [comment]
This is now on npm as `@sinonjs/samsam@2.0.0`

**Comment by mroderick** [comment]
Until the stats for `samsam` (the old package) show a steady decline, I am not going to deprecate it on npm.

https://npm-stat.com

**Comment by mroderick** [comment]
![2018-12-10 at 22 10](https://user-images.githubusercontent.com/20321/49761857-71efcd80-fcc8-11e8-9bfe-380c2a20b1ca.png)

A steady decline has been detected, and the old package has been deprecated

![2018-12-10 at 22 09](https://user-images.githubusercontent.com/20321/49761813-5258a500-fcc8-11e8-9139-6386a52047d6.png)
