### ISSUE TITLE
deepEqual returns true for different promise instances

### ISSUE THREAD

**Issue by mantoni** [sinonjs/samsam#216]
-   library version : 5.3.1 (current)
-   Environment : node 14

**What did you expect to happen?**

`samsam.deepEqual` returns `false` for different promise objects.

**What actually happens**

`samsam.deepEqual` returns `true` for different promise objects.

**How to reproduce**

```js
const samsam = require('@sinonjs/samsam');

const p1 = Promise.resolve('a');
const p2 = Promise.resolve('b');
console.log(samsam.deepEqual(p1, p2)); // should return false
```

Reported in Sinon: https://github.com/sinonjs/sinon/issues/2345

**Comment by fatso83** [comment]
verified fixed by #217
