### ISSUE TITLE
[Security] Lodash vulnerability

### ISSUE THREAD

**Issue by tiwarishubham635** [sinonjs/samsam#244]
This library depends on vulnerable versions of lodash
Here is the detailed information - https://github.com/advisories/GHSA-35jh-r3h4-6jhm

Currently this library uses lodash v4.17.4 which should be updated

-   library version : 6.1.3
-   Environment : Mac OS
-   Example URL : https://github.com/advisories/GHSA-35jh-r3h4-6jhm
-   Other libraries you are using: NA

**What did you expect to happen?**
Lodash version to be >= 4.17.21

**What actually happens**
Lodash has vulnerable versions

**How to reproduce**
Navigate to package.json and look for lodash version

**Comment by fatso83** [comment]
```
❯ npm ls --omit dev
@sinonjs/samsam@8.0.1 /Users/carlerik/dev/samsam
├── @sinonjs/commons@3.0.1
├── lodash.get@4.4.2
└── type-detect@4.1.0
```

We do not depend on anything apart from `lodash.get`, which is not affected by the CVE affecting `_.template`:
```
❯ grep template node_modules/lodash.get/index.js  | wc -l
       0
```
