### ISSUE TITLE
isDate returns true for "date-like" objects

### ISSUE THREAD

**Issue by scripter-co** [sinonjs/samsam#30]
`samsam.isDate` returns true for "[date-like](https://github.com/sinonjs/samsam/blob/master/lib/samsam.js#L68)" objects.

I don't think the following should return true:

```
it("returns true if date", function () {
    var checkDate = samsam.isDate({
        getTime: () => "hello",
        valueOf: () => "hello"
    });
    assert.isTrue(checkDate);
});
```

To be honest, i'm not overly sure the usefulness of isDate being exposed when people can simply do `(new Date) instanceof Date`

**Comment by mroderick** [comment]
`isDate` was introduced with https://github.com/sinonjs/samsam/commit/8c006bd72b1434f7f244595761f164b62c13c0e9, the commit message doesn't really give any hints as to why it was changed. It reverted https://github.com/sinonjs/samsam/commit/605df725b7a156573ef6b60454298e45b1011da0 where `isDate` was removed.

It was originally introduced in https://github.com/sinonjs/referee/commit/d607a45fcf5899260f369c95e5c2a1a0afd22c3e, to support Sinon's fake time (now [`lolex`](https://github.com/sinonjs/lolex)). Current `lolex` doesn't use `samsam`.

Considering the [few dependent packages](https://www.npmjs.com/browse/depended/samsam), I think we should go ahead and remove it, before publishing a new version.

@scripter-co would you like to create the PR to remove it?

**Comment by scripter-co** [comment]
@mroderick sure. I'll get something up.
