### ISSUE TITLE
using deepEqual on Maps always returns true

### ISSUE THREAD

**Issue by goncalo-matos** [sinonjs/samsam#67]
* library version : 3.3.1
* Environment: Node 10
* Example URL   :
* Other libraries you are using: None

**What did you expect to happen?**
`deepEqual` to return false.

**What actually happens**
It returns true.

**How to reproduce**
```javascript
const samsam = require('@sinonjs/samsam');

const a = new Map([[1,'a'], [2, 'b']]);
const b = new Map([[3,'c'], [4, 'd']]);

const a1 = new Map([[1,'a'], [2, 'b']]);

console.log(samsam.deepEqual(a, b)); // logs true
console.log(samsam.deepEqual(a, a1)); // logs true

```

**Comment by mroderick** [comment]
This has been fixed in `@sinonjs/samsam@3.3.2`
