### ISSUE TITLE
Update version of lodash to address high severity vulnerability

### ISSUE THREAD

**Issue by sievins** [sinonjs/samsam#73]
The [current version of lodash](https://github.com/sinonjs/samsam/blob/v3.3.2/package-lock.json#L4203) (4.17.11) that @sinonjs/samsam depends on has a [high severity vulnerability](https://snyk.io/vuln/SNYK-JS-LODASH-73638). Lodash applied a [fix](https://github.com/lodash/lodash/pull/4336) for 4.17.13.

The vunerablity only affects the following lodash functions, `merge`, `mergeWith` and `defaultsDeep`, which aren't actually used in this library. But it would be nice to upgrade it anyway as it would mean that consumers of @sinonjs/samsam can trust the library implicitly. At the moment GitHub alerts users of this vulnerability when installing @sinonjs/samsam and you have to manually check that the library doesn't use the above lodash functions.

* library version : 3.3.2

**What did you expect to happen?**
Not to receive a high severity vulnerability alert when installing @sinonjs/samsam.

**What actually happens**
You receive a high severity vulnerability alert when installing @sinonjs/samsam.

**How to reproduce**
```
npm i -D sinon
```

Thanks 😄

**Comment by sievins** [comment]
Ah, just noticed you already have an open [PR](https://github.com/sinonjs/samsam/pull/72) to resolve this.

Thank you 😃. Happy to close this when it's merged.

**Comment by mantoni** [comment]
PR merged. Thanks for the heads up.
