### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by geekyrajshri** [sinonjs/samsam#74]
Please upgrade the package to use the latest npm lodash package as the previous version have a vulnerability issue.

![image](https://user-images.githubusercontent.com/8193580/61767663-98e7b380-ae02-11e9-9ebb-f7d2a2150d20.png)

**Comment by mantoni** [comment]
You can simply update it yourself, either via `npm audit fix` or by re-installing your dependencies. We depend on `^4.17.11` which means the patch is loaded automatically. This module is itself built against the latest lodash since 200aa4849c682888dc4a8941a527a19aababdd41.
