### ISSUE TITLE
isArgument invalid structure causing low test coverage

### ISSUE THREAD

**Issue by mshaaban0** [sinonjs/samsam#89]
* library version : latest
* Environment : Test
* File : https://github.com/sinonjs/samsam/blob/master/lib/is-arguments.test.js and https://github.com/sinonjs/samsam/blob/master/lib/is-arguments.js

**What happened?**
While trying to increase the test coverage to 100%. I ran into this bit of code...
```js
    if (typeof object.callee === "function") {
        return true;
    }
    try {
        object[object.length] = 6;
        delete object[object.length];
    } catch (e) {
        return true;
    }
```
- Tests will never reach to `object.callee === "function"` as isArgument function will return true [here](https://github.com/sinonjs/samsam/blob/master/lib/is-arguments.js#L13)
- Same thing for `try.. catch..` isArgument will return either true or false before it reaches this point.

**Recommended Solution**
Remove the above code blocks as it is redundant.

*How to produce?*
- Run test coverage locally `npm run test:coverage` and notice the coverage result

<img width="618" alt="Screenshot 2019-09-03 at 14 07 42" src="https://user-images.githubusercontent.com/6163988/64172055-66df5d80-ce54-11e9-9070-1fc763d55a3e.png">

**Comment by mroderick** [comment]
If `getClass` can reliably detect arguments across engines, then we can simplify this method considerably.

Would you mind testing it in the engines we aim to support?

**Comment by mroderick** [comment]
This has been fixed with https://github.com/sinonjs/samsam/pull/120
